package com.github.yuanmomo.test.generator.bean;

import java.io.Serializable;

public class ToDo implements Serializable {

    /**
     * test field.
     */
    private String test;

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.to_do
     *
     * @mbg.generated
     */
    private Integer toDo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.remark
     *
     * @mbg.generated
     */
    private Long remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_to_do.id
     *
     * @return the value of table_to_do.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_to_do.id
     *
     * @param id the value for table_to_do.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_to_do.to_do
     *
     * @return the value of table_to_do.to_do
     *
     * @mbg.generated
     */
    public Integer getToDo() {
        return toDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_to_do.to_do
     *
     * @param toDo the value for table_to_do.to_do
     *
     * @mbg.generated
     */
    public void setToDo(Integer toDo) {
        this.toDo = toDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_to_do.remark
     *
     * @return the value of table_to_do.remark
     *
     * @mbg.generated
     */
    public Long getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_to_do.remark
     *
     * @param remark the value for table_to_do.remark
     *
     * @mbg.generated
     */
    public void setRemark(Long remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ToDo other = (ToDo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId())) && (this.getToDo() == null ? other.getToDo() == null : this.getToDo().equals(other.getToDo())) && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getToDo() == null) ? 0 : getToDo().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", toDo=").append(toDo);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
