package com.github.yuanmomo.test.generator.bean;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class ToDo implements Serializable {

    public static ToDo init(Integer doValue, Long version, String remark, String longText) {
        ToDo toDo = new ToDo();
        toDo.setToDo(doValue);
        toDo.setVersion(version);
        toDo.setRemark(remark);
        toDo.setLongText(longText);
        return toDo;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.to_do
     *
     * @mbg.generated
     */
    private Integer toDo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_to_do.long_text
     *
     * @mbg.generated
     */
    private String longText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
